JHA/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace JHA.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

JHA/Pages/Index.cshtml.cs
using JHA.Pages.DataClasses;
using JHA.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace JHA.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public Data newHazard { get; set; }

        public List<Data> hazards { get; set; }

        public IndexModel()
        {
            hazards = new List<Data>();
            newHazard = new Data();
        }

        public IActionResult OnGet()
        {
            // Query and function call to request data from hazard database
            string queryString = "SELECT * FROM hazard";
            MySqlDataReader data = DBClass.dataQuery(queryString);

            // Takes read data and adds to hazards arraylist
            while (data.Read())
            {
                hazards.Add(new Data
                {
                    ID = data.GetInt32("id"),
                    Author = data.GetString("author"),
                    Name = data.GetString("name"),
                    Steps = data.GetString("steps"),
                    Consequences = data.GetString("consequences"),
                    Controls = data.GetString("controls"),
                    Training = data.GetString("training"),
                    Equipment = data.GetString("equipment")
                });
            }

            // Close the connection and display the page
            DBClass.connection.Close();
            return Page();
        }

        public IActionResult OnPostCreate()
        {
            // Query to add new task and corresponding data into database
            string queryString = $"INSERT INTO hazard (author, name, steps, consequences, controls, training, equipment) " +
                                 $"VALUES ('{newHazard.Author}', '{newHazard.Name}', '{newHazard.Steps}', '{newHazard.Consequences}', " +
                                 $"'{newHazard.Controls}', '{newHazard.Training}', '{newHazard.Equipment}')";

            // Execute the INSERT query
            DBClass.dataInsert(queryString);

            // Close the connection and display the page with updated information
            DBClass.connection.Close();
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostEdit()
        {
            // Query to update all data left in the text fields within the editing modal
            // *Note* that if the user does not change anything it will overwrite the data with the same information
            string queryString = $"UPDATE hazard SET author = '{newHazard.Author}', name = '{newHazard.Name}', steps = '{newHazard.Steps}', consequences = '{newHazard.Consequences}'," +
                                 $" controls = '{newHazard.Controls}', training = '{newHazard.Training}', " +
                                 $" equipment = '{newHazard.Equipment}' WHERE id = {newHazard.ID}";

            // Execute the UPDATE query
            DBClass.dataInsert(queryString);

            // Close the connection and display the page with updated information
            DBClass.connection.Close();
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostRemove()
        {
            // Query to remove the data associated with the task name selected, by returning the ID number tied to the task name
            string queryString = $"DELETE FROM hazard WHERE id = {newHazard.ID}";

            // Execute the UPDATE query
            DBClass.dataInsert(queryString);

            // Close the connection and display the page with updated information
            DBClass.connection.Close();
            return RedirectToPage("./Index");
        }
    }
}

JHA/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace JHA.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

JHA/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1 class="display-4 text-center titletxt">Job Hazard Analysis Portal</h1>
<hr />
<div class="colcontainer">
    <div class="leftcol">
        <h1 class="titletxt text-center">Tasks</h1>
        <hr />
        @foreach (var name in Model.hazards)
        {
            <div class="namecard text-center fontbebas" onclick="displayTaskInfo('@name.Author', '@name.Name', '@name.Steps', '@name.Consequences', '@name.Controls', '@name.Training', '@name.Equipment')"
                 onmouseover="highlight(this)" onmouseout="nothighlighted(this)">
                <p>@name.Name</p>
            </div>
        }
    </div>
    <div class="rightcol">
        <h1 class="titletxt text-center">Information</h1>
        <hr />
        <div id="info" class="infobox">
            <p class="fontub text-center">Click on a task to view information</p>
        </div>
    </div>
</div>

<button type="button" class="btn-dark" data-bs-toggle="modal" data-bs-target="#modalCreate">Create A Task</button>
<button type="button" class="btn-dark" data-bs-toggle="modal" data-bs-target="#modalEdit">Edit A Task</button>
<button type="button" class="btn-dark" data-bs-toggle="modal" data-bs-target="#modalRemove">Remove A Task</button>

<!-- Modal for creation of tasks -->
<div class="modal fade fontub" id="modalCreate" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Enter Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" asp-page-handler="Create" asp-route-handler="OnPostCreate">
                    <input type="hidden" asp-for="@Model.newHazard" />
                    <div class="form-group">
                        <label>Author Name</label>
                        <textarea asp-for="@Model.newHazard.Author" id="txtauthor" class="form-control" rows="1" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Task Name</label>
                        <textarea asp-for="@Model.newHazard.Name" id="txtname" class="form-control" rows="1" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Steps to Complete</label>
                        <textarea asp-for="@Model.newHazard.Steps" id="txtsteps" class="form-control" rows="3" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Consquences of hazard</label>
                        <textarea asp-for="@Model.newHazard.Consequences" id="txtcons" class="form-control" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Controls</label>
                        <textarea asp-for="@Model.newHazard.Controls" id="txtcontrols" class="form-control" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Training</label>
                        <textarea asp-for="@Model.newHazard.Training" id="txttraining" class="form-control" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Required Equipment</label>
                        <textarea asp-for="@Model.newHazard.Equipment" id="txtequip" class="form-control" rows="2"></textarea>
                    </div>
                    <button type="button" onclick="clearForm()" class="btn-dark">Clear</button>
                    <input type="submit" value="Submit" class="btn-dark" />
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal for editing tasks -->
<div class="modal fade fontub" id="modalEdit" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit Information</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="taskForm" method="post" asp-page-handler="Edit" asp-route-handler="OnPostEdit">
                    <label>Please select a task to edit</label>
                    <select class="newlogfield dropbox" id="taskSelect" asp-for="@Model.newHazard.ID">
                        <option value="">Select a Task</option>
                        @foreach (var hazard in Model.hazards)
                        {
                            <option value="@hazard.ID">@hazard.Name</option>
                        }
                    </select>
                    <br />
                    <div class="form-group">
                        <label>Author Name</label>
                        <textarea asp-for="@Model.newHazard.Author" class="form-control" rows="1" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Task Name</label>
                        <textarea asp-for="@Model.newHazard.Name" class="form-control" rows="1" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Steps to Complete</label>
                        <textarea asp-for="@Model.newHazard.Steps" class="form-control" required></textarea>
                    </div>
                    <div class="form-group">
                        <label>Consquences of hazard</label>
                        <textarea asp-for="@Model.newHazard.Consequences" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Controls</label>
                        <textarea asp-for="@Model.newHazard.Controls" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Training</label>
                        <textarea asp-for="@Model.newHazard.Training" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Required Equipment</label>
                        <textarea asp-for="@Model.newHazard.Equipment" class="form-control"></textarea>
                    </div>
                    <input type="submit" value="Submit" class="btn-dark" />
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal for removal of tasks -->
<div class="modal fade fontub" id="modalRemove" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Hazard</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="removeForm" method="post" asp-page-handler="Remove" asp-route-handler="OnPostRemove">
                    <label asp-for="newHazard.Name">Pick a Task to Remove</label>
                    <select class="newlogfield dropbox" asp-for="newHazard.ID">
                        <option value="">Select a Task</option>
                        @foreach (var hazard in Model.hazards)
                        {
                            <option value="@hazard.ID">@hazard.Name</option>
                        }
                    </select>
                    <br />
                    <input type="submit" value="Submit" class="btn-dark" />
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    // Function to clear the form
    function clearForm() {
        document.getElementById("txtname").value = "";
        document.getElementById("txtauthor").value = "";
        document.getElementById("txtsteps").value = "";
        document.getElementById("txtcons").value = "";
        document.getElementById("txtcontrols").value = "";
        document.getElementById("txttraining").value = "";
        document.getElementById("txtequip").value = "";
    }

    // Used to display the information in relation to selected
    // Additionally, created to not bloat the HTML
    function displayTaskInfo(author, name, steps, consequences, controls, training, equipment) {
        var infoHtml = 
            "<h2 class='titletxt' style='text-decoration: underline'>" + name + "<h2>" +
            "<p class='smalltxt'>Written by " + author + "</p>" +
            "<h4 class='titletxt'>Steps to Complete this Task:</h4>" + steps +
            "<br /><br /><h4 class='titletxt'>Consequences:</h4>" + consequences +
            "<br /><br /><h4 class='titletxt'>Controls to Mitigate:</h4>" + controls +
            "<br /><br /><h4 class='titletxt'>Training:</h4>" + training +
            "<br /><br /><h4 class='titletxt'>Required Equipment:</h4>" + equipment;
        document.getElementById("info").innerHTML = infoHtml;
    }

    // Adds highlight effect when hovering over tasks
    function highlight(element) {
        element.style.background = "linear-gradient(to right, #24253B, gold, #24253B)"
        element.style.color = "black"
    }

    // Removes highlight effect when unhovering over tasks
    function nothighlighted(element) {
        element.style.background = ""
        element.style.color = ""
    }
</script>

JHA/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JHA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JHA.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Urbanist" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3">
            <div class="container fontbebas">
                <a class="navbar-brand" asp-page="/Index">ACME</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted text-center">
        <div class="container">
            &copy; 2024 - JHA - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>